
version: '3.7'

services:

  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    container_name: tree-web-dev-container
    image: tree-web-dev-image
    ports:
      - 8000:8000
    volumes:
      - .:/srv/app
      - ../tree-volumes/media:/tree-volumes/media
      - ../tree-volumes/db:/tree-volumes/db
    command: /srv/start

    restart: always
    env_file:
      - .env

#  frontend:
#    container_name: frontend
#    build:
#      context: ./frontend
     #dockerfile: ./frontend/Dockerfile
#    volumes:
#      - ./frontend:/app
      #- /app/node_modules
#    ports:
#      - 3001:3000
#    environment:
#      - CHOKIDAR_USEPOLLING=true
