version: '3.7'

services:

  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    container_name: tree-web-prod-container
    image: tree-web-prod-image
    ports:
      - 8000:8000
    volumes:
      - .:/srv/app
      - ../tree-volumes/media:/tree-volumes/media
      - ../tree-volumes/static:/tree-volumes/static
      - ../tree-volumes/db:/tree-volumes/db
    command: /srv/start

    restart: always
    env_file:
      - .env

  nginx:
    image: nginx:1.17.6-alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./compose/production/nginx:/etc/nginx/conf.d
      - ../tree-volumes/static:/tree-volumes/static
      - ../tree-volumes/media:/tree-volumes/media
    links:
      - django:django
#  frontend:
#    container_name: frontend
#    build:
#      context: ./frontend
     #dockerfile: ./frontend/Dockerfile
#    volumes:
#      - ./frontend:/app
      #- /app/node_modules
#    ports:
#      - 3001:3000
#    environment:
#      - CHOKIDAR_USEPOLLING=true
